// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVTD8Clx6n-yRNng1aeFrmo5FADdw3nA',
    appId: '1:679859902562:web:c61af75d5949bafc54193b',
    messagingSenderId: '679859902562',
    projectId: 'spotify-clone-020823',
    authDomain: 'spotify-clone-020823.firebaseapp.com',
    storageBucket: 'spotify-clone-020823.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVUqz8SUhqdzoXwC8b426W0va83KEU03Y',
    appId: '1:679859902562:android:523a78d26116840254193b',
    messagingSenderId: '679859902562',
    projectId: 'spotify-clone-020823',
    storageBucket: 'spotify-clone-020823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwWP0kvvQ9NvPls_vYYqgmPyX8cq-00A',
    appId: '1:679859902562:ios:4e604acf64b5f19d54193b',
    messagingSenderId: '679859902562',
    projectId: 'spotify-clone-020823',
    storageBucket: 'spotify-clone-020823.appspot.com',
    iosClientId: '679859902562-dg2qq2acktbn704dvoac0rprcu3i29u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwWP0kvvQ9NvPls_vYYqgmPyX8cq-00A',
    appId: '1:679859902562:ios:c441bc1ea84ed57d54193b',
    messagingSenderId: '679859902562',
    projectId: 'spotify-clone-020823',
    storageBucket: 'spotify-clone-020823.appspot.com',
    iosClientId: '679859902562-tr6hshi74fvma5pds6do16ncohbio2go.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone.RunnerTests',
  );
}
